# Skip PATH in the Security Scanning Repo - https://github.com/marekboodt/Security-Scanning-Repo 
skip-path:
  - .github/workflows/DEV/
  - .github/workflows/OLD/
  
# Testing to "accept" risks / vulnerabilities
skip-check:
## AWS ##
  - CKV_AWS_23  # Reason: This S3 bucket doesn't need versioning due to data retention policy
  - CKV_AWS_382
  - CKV_AWS_129
## AZURE ##
  - CKV_AZURE_141 
## GCP ##
  - CKV_GCP_53
