name: Terraform Checkov Scan           # workflow name

######## IMPORTANT ######## 
# Variables to set:
# type - must be set - what type of scan, [SCA, SAST, DAST, IAC]
# language - Must be set of the code must be set to know which Scanning Type / File will be used
# project_dir - Must be set to knw know which Directory to scan, " ./ " will be the default. 
# environment - Must be set to know if the pipeline should stop or continue on error - non-prod has 'continue-on-error: true' all other environments will be stopped if the scans give an error.
# non-prod has 'continue-on-error: true' all other environments will be stopped if the scans give an error-code that is not "0" !!!

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  IAC-Workflow:
    uses: marekboodt/Security-Scanning-Repo/.github/workflows/iac-workflow2.yml@main
    # uses: marekboodt/Security-Scanning-Repo/.github/workflows/iac-workflow.yml@main
    # uses: marekboodt/Security-Scanning-Repo/.github/workflows/copy-of-iac-workflow-copy.yml@main
    
    with:
      type: iac
      language: terraform
      project_dir: ./
      # non-prod has 'continue-on-error: true' all other environments will be stopped if the scans give an error.
      environment: non-prod
